export const CREATE_COMPANY_SUCCESS = "CREATE_COMPANY_SUCCESS";
export const INIT_COMPANY_SUCCESS = "INIT_COMPANY_SUCCESS";

export const SHOW_CREATE_BUTTON = "SHOW_CREATE_BUTTON";

export const INIT_EMPLOYEES = "INIT_EMPLOYEES";
export const SET_EMPLOYEES = "SET_EMPLOYEES";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_START = "ADD_EMPLOYEE_START";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_DESCRIPTION_SUCCESS =
  "ADD_EMPLOYEE_DESCRIPTION_SUCCESS";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const GET_USER_PHOTO_SUCCESS = "GET_USER_PHOTO_SUCCESS";

export const ADD_NOTE_SUCCESS = "ADD_NOTE_SUCCESS";
